import Image from "next/image";
import SocialDock from "./social-dock";

const menu = [["About","/about"],["Work","/work"],["Thinking","/thinking"]];
const Arrow = () => <span aria-hidden="true">↗</span>;
const emphasisTerms = ["월 1억 원","12%에서 18%","78%에서 82%","기존 대비 200%","200%","27%에서 4%","600%","전국 15개 캠프","14단계 안종합검진","세이프닥·원모아","세이프닥 복지몰","밀리패스","CPS 광고","CPA 광고","캠퍼스 DID 광고","상담·예약·내원","상담 기록","이탈 원인","예약 CTA","상담 스크립트","구매 전 확인 이미지","표준 난이도 가이드"];
const emphasisPattern = new RegExp(`(${emphasisTerms.join("|")})`, "g");
function EmphasisText({text}:{text:string}){return <>{text.split(emphasisPattern).map((part,index)=>emphasisTerms.includes(part)?<strong className="case-emphasis" key={`${part}-${index}`}>{part}</strong>:part)}</>}

const workCases = [
  {no:"01",type:"",title:"텔레마케팅 상담데이터를 분석하여\n예약전환율을 높였습니다",metric:"12→18%",label:"DB 예약 전환율",image:"/portfolio/case-01-db-funnel.png",problem:"월 1억 원 규모의 광고로 DB는 확보했지만 상담 이후 예약으로 이어지는 비율이 낮았고, 지점·채널별 이탈 사유도 일관된 기준 없이 관리되고 있었습니다.",insight:"광고부터 상담·예약·내원까지 같은 퍼널로 연결하고, 상담 기록을 표준화해 이탈 원인별 대응 방식을 운영하는 구조로 전환했습니다.",process:["채널·지점별 DB 유입과 상담·예약 전환율을 주 단위 퍼널로 정리했습니다.","상담 기록을 연락 지연·정보 부족·비용 문의·예약 보류 등 실제 이탈 원인으로 다시 분류했습니다.","반복 질문에 대한 안내 메시지와 상담 스크립트를 만들고 상담 후 예약 제안 시점을 앞당겼습니다.","변경 전후 전환율을 비교해 성과가 확인된 상담 방식을 지점별 운영 기준으로 적용했습니다."],result:"상담데이터 분석을 통해 문제점을 도출하고 이탈을 줄여 예약 전환율을 12%에서 18%로 개선했습니다."},
  {no:"02",type:"",title:"코디네이터 상담데이터 분석을 통해\n치료동의율을 높였습니다.",metric:"78→82%",label:"치료 동의율",image:"/portfolio/case-02-consultation.png",problem:"예약과 내원은 발생했지만 상담 이후 치료를 보류하거나 거절하는 이유가 체계적으로 구분되지 않아 코디네이터별 설명과 후속 대응에 차이가 있었습니다.",insight:"거절·보류 사유와 고객 질문을 데이터로 표준화하고, 치료 판단에 필요한 정보를 같은 순서로 설명하는 상담 프로세스로 개선했습니다.",process:["코디네이터 상담 기록에서 치료 거절·보류 사유와 반복 질문을 유형별로 정리했습니다.","비용·치료 과정·기대 결과·사후 관리 등 고객의 판단을 막는 정보 공백을 구간별로 확인했습니다.","질환과 치료별 설명 순서, 상담 스크립트와 후속 안내 메시지를 같은 기준으로 재구성했습니다.","지점별 치료 동의율과 보류 사유를 추적하며 설명이 부족한 상담 구간을 반복 보완했습니다."],result:"고객이 치료를 결정하는 데 필요한 정보와 상담 방식을 개선해 치료동의율을 78%에서 82%로 높였습니다."},
  {no:"03",type:"",title:"워드프레스 홈페이지 리뉴얼을 통해\n전환율을 높였습니다.",metric:"+200%",label:"홈페이지 예약 전환",image:"/portfolio/case-03-booking-ux.png",problem:"랜딩페이지와 홈페이지의 질환 정보·신뢰 요소·예약 CTA가 분산되어 방문자가 정보를 확인한 뒤에도 상담과 예약까지 자연스럽게 이동하기 어려웠습니다.",insight:"워드프레스 페이지를 고객의 탐색 순서에 맞춰 재구성하고 모든 핵심 페이지의 예약 진입 방식을 일관되게 연결했습니다.",process:["페이지별 유입과 예약 행동을 비교해 이탈이 크거나 예약 동선이 끊기는 화면을 찾았습니다.","질환 정보·의료진 신뢰 요소·상담 안내·예약 CTA의 우선순위를 고객 질문 순서로 재배치했습니다.","모바일 버튼 위치와 문구를 단순화하고 페이지별 상담·예약 진입 경로를 동일하게 구성했습니다.","리뉴얼 전후 예약 데이터를 비교하며 전환이 낮은 페이지의 카피와 UI를 반복 개선했습니다."],result:"워드프레스 홈페이지의 정보 구조와 예약 동선을 개선해 예약 전환을 기존 대비 200% 높였습니다."},
  {no:"04",type:"",title:"검진 프로그램을 기획해\n중장년 고객 접점을 넓혔습니다.",metric:"+200%",label:"검진·노안 상담 증가",image:"/portfolio/eye-exam-program.jpg",problem:"브랜드 콘텐츠가 20·30대 시력교정에 집중되어 40대 이상 고객의 백내장·노안·실명질환 고민을 설명할 정보와 신뢰 접점이 부족했습니다.",insight:"안질환 정보를 안종합검진 프로그램과 상담회·건강강좌로 연결해 중장년 고객이 질환을 이해하고 직접 검진을 선택할 수 있는 경험을 만들었습니다.",process:["40대 이상 고객의 백내장·황반변성·녹내장 관련 질문과 상담 현장의 요구를 수집했습니다.","14단계 안종합검진의 구성과 카탈로그 문구를 기획하고 질환별 검사 필요성을 고객 언어로 정리했습니다.","의료진 강의자료와 홈페이지 질환 안내 콘텐츠를 제작해 온·오프라인 설명 기준을 통일했습니다.","상담회와 안건강강좌를 운영해 현장 질문을 내원·검진 상담으로 연결하고 콘텐츠를 보완했습니다."],result:"안종합검진과 노안 상담이 200% 증가했고, 중장년 안질환 분야의 브랜드 접점을 넓혔습니다."},
  {no:"05",type:"",title:"질환 정보를 다시 설계해\n홈페이지 이해도를 높였습니다.",metric:"WEB UX",label:"의료 콘텐츠 구조 개선",image:"/portfolio/medical-content-guide.jpg",problem:"전문적인 질환 설명은 있었지만 고객이 증상과 치료 과정을 한눈에 이해하고 다음 행동을 결정하기 어려웠습니다.",insight:"의학 정보의 양보다 고객의 질문 순서에 맞춘 구조와 시각 자료가 이해와 상담 전환에 더 중요했습니다.",process:["결막이완증 등 실제 상담에서 반복되는 질문을 기준으로 필요한 정보를 선별했습니다.","증상→검사→치료 원리→치료 과정 순으로 홈페이지 정보 구조를 재배치했습니다.","디자이너와 협업해 의료 이미지를 고객이 이해하기 쉬운 설명형 콘텐츠로 구성했습니다.","상담 현장에서 새 페이지를 활용하고 추가 질문을 수집해 문구와 순서를 다듬었습니다."],result:"전문 정보를 고객의 질문 흐름으로 바꾸어 홈페이지와 상담에서 함께 사용할 수 있는 설명 기반을 만들었습니다."},
  {no:"06",type:"",title:"강의 자료와 현장을 운영해\n미군 가족의 내원을 만들었습니다.",metric:"B2B·B2C",label:"설명회·내원 프로젝트",image:"/portfolio/us-forces-seminar.jpg",problem:"주한미군과 가족은 언어와 의료 정보의 장벽 때문에 국내 안과 진료와 수술을 결정하기 어려웠습니다.",insight:"광고보다 직접 질문할 수 있는 영어 설명회와 신뢰할 수 있는 현장 안내가 행동 전환에 효과적이라고 판단했습니다.",process:["대상 고객이 궁금해하는 수술·회복·검진 질문을 정리해 영문 강의 흐름을 설계했습니다.","의료진 강의 자료와 현장 안내물을 제작하고 통역·상담 동선을 준비했습니다.","설명회 현장을 운영하며 개별 질문을 상담으로 연결했습니다.","행사 후 관심 고객의 방문 검진과 내원 과정을 이어서 관리했습니다."],result:"주한미군과 가족 대상 설명회·진료 프로젝트를 운영하고 정보 탐색부터 내원까지 이어지는 오프라인 고객 경험을 구축했습니다."},
  {no:"07",type:"",title:"복지 플랫폼 광고를 확장해\n신규 내원 채널을 만들었습니다",metric:"+600%",label:"제휴 채널 매출 성장",image:"/portfolio/welfare-platform-campaign.jpg",problem:"기존 협약처 중심의 홍보만으로는 비협약 대학생과 군인·군인가족에게 병원의 시력교정·노안 혜택을 알리기 어려웠고, 신규 내원 채널도 제한적이었습니다.",insight:"세이프닥·원모아의 대학·기업 이용자와 밀리패스의 군인 이용자를 구분해 성과형 광고를 운영하고, 대학 DID와 오프라인 접점을 함께 확장했습니다.",process:["대학생·기업 구성원·군인 및 가족으로 타깃을 구분하고 채널별 이용자와 광고 과금 구조를 비교했습니다.","세이프닥·원모아에는 CPS 광고를, 밀리패스에는 CPA 광고를 적용해 혜택과 상담 연결 방식을 설계했습니다.","비협약 대학생 접점을 확보하기 위해 캠퍼스 DID 광고를 집행하고 세이프닥과 오프라인 행사를 병행했습니다.","문의·상담·활동 전환과 채널 매출을 월별로 추적하며 성과가 확인된 복지 플랫폼 운영을 확대했습니다."],result:"세이프닥 복지몰 채널 매출을 약 2,600만 원에서 1억 5,200만 원으로 성장시켜 600% 이상의 성과를 만들었습니다."},
  {no:"08",type:"",title:"복지관 현장 행사를 운영해\n중장년 고객을 직접 만났습니다.",metric:"FIELD",label:"제휴 행사·현장 상담",image:"/portfolio/community-field-event.jpg",problem:"온라인 정보만으로는 중장년 고객의 구체적인 눈 건강 고민과 진료 장벽을 파악하기 어려웠습니다.",insight:"고객이 있는 현장으로 찾아가 직접 질문을 듣고 바로 설명하는 접점이 신뢰 형성과 후속 상담에 효과적이었습니다.",process:["대학·기업·복지관의 참여자 특성과 행사 목적에 맞춰 상담 주제와 운영 동선을 정했습니다.","검진·노안·백내장 정보를 간결한 판넬과 안내물로 제작했습니다.","현장에서 고객 질문을 듣고 필요한 검진과 진료 정보를 1:1로 안내했습니다.","반복 질문과 고객 반응을 정리해 다음 행사 콘텐츠와 상담 방식을 개선했습니다."],result:"제휴처 현장에서 실제 고객 니즈를 수집하고 상담과 내원으로 이어질 수 있는 오프라인 마케팅 운영 방식을 정립했습니다."},
  {no:"09",type:"",title:"판촉물을 정보 도구로 바꿔\n상담 시작점을 만들었습니다.",metric:"1 SHEET",label:"고객 안내물 기획",image:"/portfolio/customer-guide.jpg",problem:"기존 판촉은 증정품 중심이어서 고객이 병원의 장점과 자신에게 필요한 진료 정보를 기억하기 어려웠습니다.",insight:"받고 끝나는 판촉물보다 혜택·검진 정보·상담 연결 정보를 한 장에 담은 도구가 현장 대화를 시작하기에 적합했습니다.",process:["현장에서 고객이 가장 많이 묻는 시력교정·노안·백내장 질문을 추렸습니다.","혜택과 핵심 진료 정보를 한눈에 볼 수 있도록 양면 안내물 구조를 기획했습니다.","상담 담당자가 바로 활용할 수 있게 진료별 메시지와 QR·연락 동선을 정리했습니다.","인쇄 단가와 현장 휴대성을 고려해 기존 판촉 구성을 간소화했습니다."],result:"고객에게 정보를 설명하고 후속 상담으로 연결할 수 있는 실용적인 현장 안내 도구를 만들었습니다."},
  {no:"10",type:"",title:"VOC를 분석해 고객 여정 프로세스를 개선,\n납기 연기와 취소율을 낮췄습니다.",metric:"27→4%",label:"설치 취소율",image:"/portfolio/installation-guide-visual.png",problem:"고객이 빌트인 가전의 설치 조건을 모른 채 주문해 방문 당일 설치 불가·취소·반품이 반복됐고, 설치기사와 물류센터의 운영 피로도도 높았습니다.",insight:"전국 15개 캠프의 VOC를 제품과 설치 환경별로 표준화하고, 필수 설치 조건을 구매 전에 확인할 수 있는 구조로 고객 여정을 앞당겼습니다.",process:["전국 15개 캠프의 취소·환불 VOC를 제품·설치 환경·고객 기대 차이 기준으로 재분류했습니다.","전기레인지·가스레인지·직수형 정수기에서 반복되는 주문 실수와 설치 불가 조건을 도출했습니다.","가스 종류·타공 크기·원수 거리 등 필수 조건을 상세페이지의 구매 전 확인 이미지로 제작했습니다.","설치 협력사 교육과 표준 난이도 가이드를 운영하며 캠프별 설치 품질과 취소율을 추적했습니다."],result:"구매 전 안내와 설치 운영 기준을 개선해 설치 취소율을 27%에서 4%로 낮추고 불필요한 반품과 재방문을 줄였습니다."},
];

// 병원·의료 마케팅 채용 흐름: 사업/채널 구축 → 퍼널 개선 → 서비스 기획 → 상담 CX → 협업 실행 → 콘텐츠와 현장 운영.
const rankedWorkCases = ["07", "01", "03", "04", "02", "10"]
  .map((no) => workCases.find((item) => item.no === no))
  .filter((item): item is (typeof workCases)[number] => Boolean(item))
  .map((item, index) => ({ ...item, no: String(index + 1).padStart(2, "0") }));

function Header({active}:{active:"work"|"thinking"}){return <header className="site-header detail-header editorial-header"><a className="wordmark" href="/"><Image src="/xbase-header-logo.svg" alt="XBASE" width={99} height={26} priority /></a><nav aria-label="주요 메뉴">{menu.map(([label,href])=><a className={href===`/${active}`?"active":""} href={href} key={href}>{label}</a>)}</nav><details className="mobile-menu"><summary aria-label="메뉴 열기"><span/><span/></summary><div>{menu.map(([label,href])=><a href={href} key={href}>{label}</a>)}</div></details></header>}
function Footer(){return <footer><a className="wordmark inverse" href="/"><Image src="/xbase-logo.svg" alt="" width={30} height={30}/><b>XBASE<span>.</span></b></a><p>회사와 브랜드를 식별할 수 있는 정보는 비공개 처리했습니다.</p><p>© 2026 XBASE.</p></footer>}

export function WorkPage(){return <main className="editorial-page work-detail-page"><SocialDock/><Header active="work"/>
  <section className="sub-hero work-sub-hero"><div className="sub-hero-copy"><p className="section-kicker">SELECTED WORK</p><h1>문제를 발견하고,<br/><span>변화를 설계합니다.</span></h1><p>광고·콘텐츠·현장 운영·고객 경험을 따로 보지 않고,<br/>측정 가능한 결과로 연결한 프로젝트를 소개합니다.</p></div></section>
  <section className="case-showcase-list">{rankedWorkCases.map((item,caseIndex)=><article className={`case-showcase ${caseIndex%2?"reverse":""}`} id={`case-${item.no}`} key={item.no}><div className="case-showcase-inner"><header><div className="case-showcase-meta"><b>{item.type}</b><div className="case-showcase-thumb"><Image src={item.image} alt="회사 식별 정보를 제거한 프로젝트 썸네일" fill sizes="(max-width: 680px) 100vw, 260px"/></div></div><h2>{item.title.split("\n").map(x=><span key={x}>{x}</span>)}</h2><div className="case-showcase-metric"><strong>{item.metric}</strong><p>{item.result}</p></div></header><details className="case-showcase-details"><summary><b>과정 자세히 보기</b><i>+</i></summary><div className="case-showcase-detail-body"><div className="case-detail-visual"><Image src={item.image} alt="회사 식별 정보를 제거한 프로젝트 대표 이미지" fill sizes="(max-width: 680px) 100vw, 440px"/><div className="case-detail-visual-result"><span>RESULT</span><strong>{item.metric}</strong><p><EmphasisText text={item.result}/></p></div></div><div className="case-detail-content"><div className="case-detail-heading"><h2>{item.title.split("\n").map(x=><span key={x}>{x}</span>)}</h2><span>PROJECT {item.no}</span></div><div className="case-detail-summary"><section className="as-is"><b>AS-IS</b><p><EmphasisText text={item.problem}/></p></section><section className="to-be"><b>TO-BE</b><p><EmphasisText text={item.insight}/></p></section></div><div className="case-detail-process"><h3>HOW</h3><ol>{item.process.map((step,index)=><li key={step}><b>{String(index+1).padStart(2,"0")}</b><p><EmphasisText text={step}/></p></li>)}</ol></div></div></div></details></div></article>)}</section>
  <section className="editorial-next"><p className="section-kicker">NEXT</p><h2>결과보다 먼저 있었던<br/>생각을 기록합니다.</h2><a href="/thinking">THINKING 보기 <Arrow/></a></section><Footer/></main>}

export function ThinkingPage(){return <main className="editorial-page thinking-detail-page"><SocialDock/><Header active="thinking"/>
  <section className="sub-hero thinking-sub-hero"><div className="sub-hero-copy"><p className="section-kicker">THINKING / NOTES</p><h1>관찰한 것을 기록하고,<br/><span>다음 질문으로 연결합니다.</span></h1><p>마케팅, 데이터, AI와 일하는 방식에 대해<br/>현장에서 배운 생각을 정리합니다.</p></div><div className="sub-hero-media"><Image src="/portfolio/thinking-editorial-anonymized.png" alt="익명화된 리서치와 콘텐츠 기획 자료" fill priority sizes="(max-width: 680px) 100vw, 52vw"/><span>FIELD NOTES · 2026</span></div></section>
  <section className="blog-staging"><div className="blog-staging-head"><div><p className="section-kicker">ARCHIVE</p><h2>생각과 기록이<br/>쌓일 공간입니다.</h2></div><p>게시글과 블로그 콘텐츠를 순차적으로 정리해 공개할 예정입니다.</p></div><div className="blog-categories" aria-label="예정 카테고리"><span>ALL</span><span>MARKETING</span><span>DATA</span><span>AI & WORK</span><span>FIELD NOTES</span></div><div className="blog-empty"><span>COMING SOON</span><h3>첫 번째 기록을<br/>준비하고 있습니다.</h3><p>현재는 아카이브 구조만 정리되어 있습니다.</p><a href="https://www.threads.com/@xbase_lab?hl=ko" target="_blank" rel="noreferrer">THREADS 바로가기 <Arrow/></a></div></section>
  <section className="editorial-next thinking-next"><p className="section-kicker">SELECTED WORK</p><h2>먼저, 실행으로 만든<br/>결과를 확인해 보세요.</h2><a href="/work">WORK 보기 <Arrow/></a></section><Footer/></main>}
