import Image from "next/image";
import SocialDock from "./social-dock";

const menu = [["About","/about"],["Work","/work"],["Thinking","/thinking"]];
const Arrow = () => <span aria-hidden="true">↗</span>;

const workCases = [
  {no:"01",type:"PERFORMANCE · FULL FUNNEL",title:"광고 유입을 넘어,\n예약과 동의까지 개선했습니다.",metric:"12→18%",label:"DB 예약 전환율",image:"/portfolio/thinking-editorial-anonymized.png",problem:"월 1억 원 규모의 퍼포먼스 광고가 유입을 만들고 있었지만 상담·예약·내원·치료 동의 단계의 이탈 원인이 분리되어 관리되지 않았습니다.",insight:"광고 효율만 높이는 것보다 고객이 결정을 내리는 전 과정의 정보와 커뮤니케이션 공백을 함께 줄여야 최종 성과가 커진다고 판단했습니다.",process:["채널별 광고 성과와 DB를 연결해 유입→상담→예약→내원→동의 퍼널을 지점별로 정리했습니다.","상담 질문과 이탈 사유를 모아 랜딩 정보 부족, 예약 안내, 상담 커뮤니케이션 문제로 나눴습니다.","질환별 콘텐츠와 랜딩 UX를 고치고 CTA 순서, 상담 스크립트, 고객 안내 메시지를 함께 개선했습니다.","주 단위 전환율을 비교하며 지점별 차이를 점검하고 성과가 확인된 방식을 반복 적용했습니다."],result:"DB 예약 전환율을 12%에서 18%로, 치료 동의율을 78%에서 82%로 개선했습니다. 홈페이지 예약 전환은 기존 대비 200% 향상됐습니다.",proof:["홈페이지 예약 +200%","치료 동의 78→82%"],role:"풀퍼널 분석 · 랜딩 UX · 상담 프로세스 · 콘텐츠 기획",tools:"GA4 · Google Ads · Meta · Excel · Figma"},
  {no:"02",type:"MEDIA · GROWTH",title:"새로운 채널을 실험해\n매출 접점을 확장했습니다.",metric:"+600%",label:"신규 채널 매출 성장",image:"/portfolio/work-funnel-anonymized.png",problem:"기존 매체에 예산과 고객 접점이 집중되어 신규 고객군을 안정적으로 확보하기 어려웠습니다.",insight:"고객의 일상과 가까운 제휴 채널에서 정보와 혜택을 함께 제공하면 신뢰와 전환을 동시에 만들 수 있다고 판단했습니다.",process:["기존 채널별 유입·문의·매출을 비교해 확장 여지가 낮은 구간을 먼저 제외했습니다.","타깃의 생활 반경과 관심사를 기준으로 후보 매체와 제휴처를 발굴하고 우선순위를 정했습니다.","채널별 소재와 메시지를 달리 제작하고 랜딩·오프라인 협업까지 하나의 실험 단위로 운영했습니다.","주간 매출과 전환 데이터를 기준으로 성과가 확인된 조합에 예산과 운영 자원을 재배분했습니다."],result:"신규 채널 매출이 초기 대비 600% 성장했고, 단일 매체 의존도를 낮춘 추가 매출 경로를 확보했습니다.",role:"채널 발굴 · 매체 집행 · 제휴 운영 · 매출 분석",tools:"Excel · Canva · GA4 · Media Dashboard"},
  {no:"03",type:"OFFLINE · BRAND",title:"정보를 경험으로 바꿔\n현장의 반응을 만들었습니다.",metric:"3 FORMAT",label:"상담·세미나·행사",image:"/portfolio/work-events-anonymized.png",problem:"전문 정보는 충분했지만 고객이 이해하고 질문한 뒤 실제 행동으로 옮길 수 있는 접점이 부족했습니다.",insight:"일방적인 설명보다 직접 질문하고 확인하는 경험이 신뢰 형성과 다음 행동에 더 효과적이었습니다.",process:["현장에서 반복되는 질문과 참여자의 이해 수준을 조사해 꼭 필요한 정보만 추렸습니다.","목적에 따라 1:1 상담, 교육 세미나, 참여형 행사 세 가지 포맷으로 경험을 나눴습니다.","각 포맷의 콘텐츠·제작물·동선·운영 체크리스트를 만들고 협력사 역할을 구체화했습니다.","행사 후 질문과 참여 반응을 정리해 다음 회차의 주제, 설명 순서, 안내물을 개선했습니다."],result:"서로 다른 목적의 세 가지 운영 포맷을 정착시키고, 전문 정보를 고객이 체감하는 브랜드 경험으로 전환했습니다.",role:"행사 기획 · 제작물 · 협력사 조율 · 현장 운영",tools:"PowerPoint · Canva · Figma · Excel"},
  {no:"04",type:"DATA · OPERATIONS",title:"반복되는 VOC에서\n취소의 원인을 찾았습니다.",metric:"27→4%",label:"설치 취소율 감소",image:"/portfolio/work-funnel-anonymized.png",problem:"주문 이후 설치 조건을 뒤늦게 알게 된 고객의 취소가 반복됐지만 원인이 현장 문제로만 분류되고 있었습니다.",insight:"취소 시점과 VOC를 함께 보니 품질보다 구매 전에 전달되지 않은 조건과 기대 불일치가 핵심 원인이었습니다.",process:["전국 15개 운영 거점의 취소 사유와 VOC 표현을 동일 기준으로 정리해 원인별로 재분류했습니다.","주문부터 설치까지 단계별 취소율을 비교해 정보 누락이 발생하는 지점을 특정했습니다.","상세페이지의 필수 조건을 앞단으로 옮기고 주문 직후 사전 안내 메시지와 확인 절차를 만들었습니다.","설치 난이도 분류와 표준 가이드를 만들고 거점별 적용 여부와 주간 취소율을 추적했습니다."],result:"설치 서비스 취소율을 27%에서 4%까지 낮추고, 전국 15개 거점에서 사전 정보와 설치 품질을 일관되게 관리할 기준을 만들었습니다.",proof:["전국 15개 거점","설치 표준 가이드"],role:"VOC 분석 · 원인 정의 · UX 개선 · 운영 품질 관리",tools:"Excel · Reporting · Funnel Analysis"},
  {no:"05",type:"AI · CONTENT OPERATIONS",title:"반복 제작을 줄이고,\n콘텐츠 실행 속도를 높였습니다.",metric:"AI SYSTEM",label:"블로그 자동화 구축",image:"/portfolio/thinking-editorial-anonymized.png",problem:"전문성 검토가 필요한 블로그 콘텐츠를 반복 제작하면서 주제 조사, 초안 작성, 형식 정리에 많은 시간이 들었습니다.",insight:"사람의 판단이 필요한 검수는 유지하되 반복되는 조사와 초안 구조를 AI에 맡기면 품질 기준을 지키면서 실행 속도를 높일 수 있었습니다.",process:["기존 콘텐츠의 주제, 구성, 금지 표현, 필수 검수 항목을 분석해 공통 제작 규칙을 정리했습니다.","키워드와 고객 질문을 입력하면 목차와 초안이 생성되는 단계별 프롬프트 흐름을 설계했습니다.","전문성·과장 표현·브랜드 톤을 사람이 확인하는 검수 체크포인트를 자동화 과정 사이에 배치했습니다.","실제 콘텐츠 제작에 적용하며 오류 사례를 수집하고 프롬프트와 출력 형식을 반복 보완했습니다."],result:"반복적인 초안 작업을 시스템화하고, 담당자가 검수와 고객 관점의 품질 개선에 더 집중할 수 있는 제작 기반을 만들었습니다.",role:"업무 분석 · 프롬프트 설계 · 콘텐츠 구조 · 검수 프로세스",tools:"ChatGPT · Claude · Gemini · WordPress"},
];

function Header({active}:{active:"work"|"thinking"}){return <header className="site-header detail-header editorial-header"><a className="wordmark" href="/"><Image src="/xbase-header-logo.svg" alt="XBASE" width={99} height={26} priority /></a><nav aria-label="주요 메뉴">{menu.map(([label,href])=><a className={href===`/${active}`?"active":""} href={href} key={href}>{label}</a>)}</nav><details className="mobile-menu"><summary aria-label="메뉴 열기"><span/><span/></summary><div>{menu.map(([label,href])=><a href={href} key={href}>{label}</a>)}</div></details></header>}
function Footer(){return <footer><a className="wordmark inverse" href="/"><Image src="/xbase-logo.svg" alt="" width={30} height={30}/><b>XBASE<span>.</span></b></a><p>회사와 브랜드를 식별할 수 있는 정보는 비공개 처리했습니다.</p><p>© 2026 XBASE.</p></footer>}

export function WorkPage(){return <main className="editorial-page work-detail-page"><SocialDock/><Header active="work"/>
  <section className="sub-hero work-sub-hero"><div className="sub-hero-copy"><p className="section-kicker">SELECTED WORK</p><h1>문제를 발견하고,<br/><span>변화를 설계합니다.</span></h1><p>광고·콘텐츠·현장 운영·고객 경험을 따로 보지 않고,<br/>측정 가능한 결과로 연결한 프로젝트를 소개합니다.</p></div></section>
  <section className="case-showcase-list">{workCases.map((item,caseIndex)=><article className={`case-showcase ${caseIndex%2?"reverse":""}`} id={`case-${item.no}`} key={item.no}><div className="case-showcase-inner"><header><div><span>CASE {item.no}</span><b>{item.type}</b></div><h2>{item.title.split("\n").map(x=><span key={x}>{x}</span>)}</h2><div className="case-showcase-metric"><strong>{item.metric}</strong><span>{item.label}</span></div></header><div className="case-showcase-lead"><div className="case-showcase-image"><Image src={item.image} alt="회사 식별 정보를 제거한 프로젝트 비주얼" fill sizes="(max-width: 680px) 100vw, 46vw"/></div><div className="case-showcase-copy"><section><span>01 · CONTEXT / PROBLEM</span><h3>상황과 문제 정의</h3><p>{item.problem}</p></section><section><span>02 · OBSERVATION / HYPOTHESIS</span><h3>데이터 확인과 가설</h3><p>{item.insight}</p></section></div></div><div className="case-showcase-process"><div className="case-showcase-process-title"><span>03—06 · PROCESS</span><h3>어떻게 진행했는지</h3></div><ol>{item.process.map((step,index)=><li key={step}><b>{String(index+1).padStart(2,"0")}</b><p>{step}</p></li>)}</ol></div><div className="case-showcase-result"><div><span>07 · RESULT</span><h3>검증과 결과</h3></div><strong>{item.metric}</strong><div><p>{item.result}</p>{item.proof&&<div className="case-proof">{item.proof.map(value=><span key={value}>{value}</span>)}</div>}</div></div></div></article>)}</section>
  <section className="editorial-next"><p className="section-kicker">NEXT</p><h2>결과보다 먼저 있었던<br/>생각을 기록합니다.</h2><a href="/thinking">THINKING 보기 <Arrow/></a></section><Footer/></main>}

export function ThinkingPage(){return <main className="editorial-page thinking-detail-page"><SocialDock/><Header active="thinking"/>
  <section className="sub-hero thinking-sub-hero"><div className="sub-hero-copy"><p className="section-kicker">THINKING / NOTES</p><h1>관찰한 것을 기록하고,<br/><span>다음 질문으로 연결합니다.</span></h1><p>마케팅, 데이터, AI와 일하는 방식에 대해<br/>현장에서 배운 생각을 정리합니다.</p></div><div className="sub-hero-media"><Image src="/portfolio/thinking-editorial-anonymized.png" alt="익명화된 리서치와 콘텐츠 기획 자료" fill priority sizes="(max-width: 680px) 100vw, 52vw"/><span>FIELD NOTES · 2026</span></div></section>
  <section className="blog-staging"><div className="blog-staging-head"><div><p className="section-kicker">ARCHIVE</p><h2>생각과 기록이<br/>쌓일 공간입니다.</h2></div><p>게시글과 블로그 콘텐츠를 순차적으로 정리해 공개할 예정입니다.</p></div><div className="blog-categories" aria-label="예정 카테고리"><span>ALL</span><span>MARKETING</span><span>DATA</span><span>AI & WORK</span><span>FIELD NOTES</span></div><div className="blog-empty"><span>COMING SOON</span><h3>첫 번째 기록을<br/>준비하고 있습니다.</h3><p>현재는 아카이브 구조만 정리되어 있습니다.</p><a href="https://www.threads.com/@xbase_lab?hl=ko" target="_blank" rel="noreferrer">THREADS 바로가기 <Arrow/></a></div></section>
  <section className="editorial-next thinking-next"><p className="section-kicker">SELECTED WORK</p><h2>먼저, 실행으로 만든<br/>결과를 확인해 보세요.</h2><a href="/work">WORK 보기 <Arrow/></a></section><Footer/></main>}
